services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
      - ./init-cql:/docker-entrypoint-initdb.d
    environment:
      CASSANDRA_CLUSTER_NAME: "TestCluster"
      CASSANDRA_NUM_TOKENS: "256"
      CASSANDRA_RPC_ADDRESS: "0.0.0.0"
      CASSANDRA_START_RPC: "true"
    networks:
      - app_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - cassandra
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_PORT=9042
    networks:
      - app_network

    #command: ["./wait_for_db.sh", "python", "app/main.py"]
volumes:
  cassandra_data:

networks:
  app_network: